# Generated by Django 3.0.3 on 2020-02-10 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whoduzwat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chores', to='whoduzwat.Family'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='person_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chores', to='whoduzwat.FamilyMember'),
        ),
    ]
